# Site settings
title: Tech Blog of Xi Jin
email: jincoding@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Opinions on MEAN stack and general web development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: pragmaticjin
github_username:  bosonx

# Build settings
markdown: kramdown
